/*
 *Acceso al sistema.
 *se va a dividir dos tipos de accesos: PARA CAJERO Y GERENTE
 */
package Vista;

import Controlador.Encriptacion;
import Controlador.SendMail;
import Modelo.CRUD_Acceso_al_sistema;
import DTO.DTOTrabajador;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;
/**
 * autor: Jose Marcos Luna 62529292
 */
public class Acceso_al_Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public String usuario;
    public String contraseña;

    public Acceso_al_Sistema() {
        initComponents();
        
        //colocar un icono 
        setIconImage(new ImageIcon(getClass().getResource("/iconos_Ventana_Principal/italy.png")).getImage());
        this.setResizable(false); //Quitar el maximizar y ampliar pantalla
        this.setLocationRelativeTo(null); //LA PANTALLA ESTARA EN EL CENTRO
        
        //para añadir el estilo PlaceHolder
        AgregaplaceHolder(txtUser);
        AgregaplaceHolder(txtPassword);
        
       
    }

    /***
     *     permite CREAR EL PLACE HOLDER USANDO UN JTextField
     * @param txt 
     */
      public void AgregaplaceHolder (JTextField txt)
    {
        Font font= txt.getFont();
        font = font.deriveFont(Font.ITALIC);
        txt.setFont(font);
        txt.setForeground(Color.gray); 
    }
    
      /***
       * Permite Quitar el place holder
       * @param txt 
       */
    public void QuitarplaceHolder (JTextField txt)
    {
        Font font = txt.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        txt.setFont(font);
        txt.setForeground(Color.black);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnGroupTurno = new javax.swing.ButtonGroup();
        lblUser = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnNuevo = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACCESO AL SISTEMA \"ITALY PASTELERÍA\"");
        setBackground(new java.awt.Color(85, 136, 210));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/empleados.png"))); // NOI18N
        lblUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblUser.setFocusable(false);
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUser.setIconTextGap(0);
        lblUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/clave.png"))); // NOI18N

        txtUser.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtUser.setText("Usuario");
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });

        btnIngresar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/entrar.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtPassword.setText("Password");
        txtPassword.setEchoChar('\u0000');
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/usuario.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(48, 48, 48)
                        .addComponent(btnIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser)
                            .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresar)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("Aqui inicia para ingresar al sistema");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        /*
         *creamos el objeto variables empleado y lo almacena al constructor
         *de la clase DTOTrabajador*/
        usuario = txtUser.getText();
        contraseña = txtPassword.getText();
        DTOTrabajador variables_empleado = new DTOTrabajador(usuario,contraseña);
      
        System.out.println("se envio los datos usuario: " + variables_empleado.
                getUsuario() + " contraseña: " + variables_empleado.getPassword());
        /*
         *Creamos un objeto crudaccess para enviar los datos de usuario y contraseña
        */
        CRUD_Acceso_al_sistema crudaccess = new CRUD_Acceso_al_sistema();
        crudaccess.ingreso_al_sistema(variables_empleado.getUsuario(),
                variables_empleado.getPassword());
       
        dispose();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
        if(txtPassword.getText().equals("Password")){
            txtPassword.setText(null);
            txtPassword.requestFocus();
            //añade un caracter a txtpassword
            txtPassword.setEchoChar('*');
            //quita el placegholder
            QuitarplaceHolder(txtPassword);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        
        if(txtPassword.getText().length()==0)
        {
           //agrega el placeholder
            AgregaplaceHolder(txtPassword);
            txtPassword.setEchoChar('\u0000');
            txtPassword.setText("Password");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
       this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
         if(txtUser.getText().equals("Usuario")){
            txtUser.setText(null);
            txtUser.requestFocus();
            //quita el placeholder
            QuitarplaceHolder(txtUser);
           
        }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        // TODO add your handling code here:
          if(txtUser.getText().length()==0)
        {
           //agrega el placeholder
            AgregaplaceHolder(txtUser);
            txtUser.setText("Usuario");
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Registro registro = new Registro();
        registro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed

    /*Creamos una funcion donde le dara el la aprobacion para poder ingresar al sistema*/
    public void confirmacion_al_sistema(int sw) {
        if (sw == 1) {
            System.out.println("Usuario o contraseña exitoso, ingresará a la ventana principal");
     /*         System.out.println("Enviamos correo electronico");
       SendMail mail = new SendMail();
       mail.enviarConArchivoAdjunto();
       */
            Ventana_Principal irVentanaPrincipal = new Ventana_Principal();
            irVentanaPrincipal.setVisible(true);
        }
        if (sw == 2) {
            System.out.println("Usuario o contraseña incorrecta");
            JOptionPane.showMessageDialog(null, "Usuario o contraseña erronea, intente nuevamente");
            dispose();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupTurno;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
