package Vista;

import Vista_Ventas.VentanaPrincipalVentas;
import Controlador.Tamaño_Icono;
import javax.swing.JOptionPane;

/*Es la ventana donde se puede acceder a todas las oopciones 
para poder gestionar el negocio.
inicialmente tenemos el acceso a ventas y recursos humanos*/
public class Ventana_Principal extends javax.swing.JFrame {

    public Ventana_Principal() {
        initComponents();
        this.setResizable(false); //Quitar el maximizar y ampliar pantalla
        this.setLocationRelativeTo(null); //LA PANTALLA ESTARA EN EL CENTRO

        //this.setLocationRelativeTo(this);
    
        /*importamos la clase Tamaño icono para luego crear un objeto
    luego llamamos la funcion pintar imagen para que pueda configurar el tamaño de las imagenes*/
     /*   Tamaño_Icono llamaClaseTamIcon = new Tamaño_Icono();
      
        llamaClaseTamIcon.pintarImagen(lblVentas, "src\\iconos_Ventana_Principal\\punto-de-venta.png");
        llamaClaseTamIcon.pintarImagen(lblAlmacen, "src\\iconos_Ventana_Principal\\inventario.png");
        llamaClaseTamIcon.pintarImagen(lblContabilidad, "src\\iconos_Ventana_Principal\\calculo.png");
        llamaClaseTamIcon.pintarImagen(lblMarketing, "src\\iconos_Ventana_Principal\\publicidad-online.png");
        llamaClaseTamIcon.pintarImagen(lblRecursosHumanos, "src\\iconos_Ventana_Principal\\recursos-humanos.png");
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlmacen = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnContabilidad = new javax.swing.JButton();
        btnRecursos_Humanos = new javax.swing.JButton();
        btn_Marketing = new javax.swing.JButton();
        lblAlmacen = new javax.swing.JLabel();
        lblRecursosHumanos = new javax.swing.JLabel();
        lblVentas = new javax.swing.JLabel();
        lblContabilidad = new javax.swing.JLabel();
        lblMarketing = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VENTANA PRINCIPAL");

        btnAlmacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlmacen.setText("Almacén");
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });

        btnVentas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnContabilidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnContabilidad.setText("Contabilidad");
        btnContabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContabilidadActionPerformed(evt);
            }
        });

        btnRecursos_Humanos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRecursos_Humanos.setText("Recursos Humanos");
        btnRecursos_Humanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecursos_HumanosActionPerformed(evt);
            }
        });

        btn_Marketing.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Marketing.setText("Marketing");
        btn_Marketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MarketingActionPerformed(evt);
            }
        });

        lblAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/inventario.png"))); // NOI18N
        lblAlmacen.setToolTipText("");
        lblAlmacen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlmacenMouseClicked(evt);
            }
        });

        lblRecursosHumanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/recursos-humanos.png"))); // NOI18N
        lblRecursosHumanos.setToolTipText("");
        lblRecursosHumanos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblRecursosHumanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecursosHumanosMouseClicked(evt);
            }
        });

        lblVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/punto-de-venta.png"))); // NOI18N
        lblVentas.setToolTipText("");
        lblVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
        });

        lblContabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/calculo.png"))); // NOI18N
        lblContabilidad.setToolTipText("");
        lblContabilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblContabilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContabilidadMouseClicked(evt);
            }
        });

        lblMarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Ventana_Principal/publicidad-online.png"))); // NOI18N
        lblMarketing.setToolTipText("");
        lblMarketing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMarketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMarketingMouseClicked(evt);
            }
        });
        lblMarketing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblMarketingKeyTyped(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblContabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnContabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblRecursosHumanos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRecursos_Humanos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Marketing, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(btnSalir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblContabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(lblAlmacen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnContabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecursosHumanos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecursos_Humanos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Marketing, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // ira a la ventana de Acceso_al_Sistema
        Acceso_al_Sistema irAcceso_Sistema = new Acceso_al_Sistema();
        irAcceso_Sistema.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        VentanaPrincipalVentas irVentas = new VentanaPrincipalVentas();
        irVentas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked
        // TODO add your handling code here:
        VentanaPrincipalVentas irVentas = new VentanaPrincipalVentas();
        irVentas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblVentasMouseClicked

    private void btnContabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContabilidadActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            MUY PRONTO PODRAS HACER UN SEGUIMIENTO DE TUS CUENTAS CONTABLES \r
                                             BALANCE GENERAL\r
                                             ESTADO DE RESULTADOS""");
    }//GEN-LAST:event_btnContabilidadActionPerformed

    private void lblContabilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContabilidadMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            MUY PRONTO PODRAS HACER UN SEGUIMIENTO DE TUS CUENTAS CONTABLES \r
                                             BALANCE GENERAL\r
                                             ESTADO DE RESULTADOS""");
    }//GEN-LAST:event_lblContabilidadMouseClicked

    private void lblAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlmacenMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            MUY PRONTO PODRAS HACER UN SEGUIMIENTO DE TUS PRODUCTOS \r
                                             MATERIA PRIMA\r
                                             REPORTE DE INVENTARIOS\r
                                             ADICIONAR Y EDITAR RECETAS """);
    }//GEN-LAST:event_lblAlmacenMouseClicked

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            MUY PRONTO PODRAS HACER UN SEGUIMIENTO DE TUS PRODUCTOS \r
                                             MATERIA PRIMA\r
                                             REPORTE DE INVENTARIOS\r
                                             ADICIONAR Y EDITAR RECETAS """);

    }//GEN-LAST:event_btnAlmacenActionPerformed

    private void lblRecursosHumanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecursosHumanosMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            MUY PRONTO PODRAS \r
                                             HACER UN SEGUIMIENTO DE TUS COLABORADORES \r
                                             EL HOARIO DE ASISTENCIA \r
                                             Y PLANILLA DE SUELDOS Y SALARIOS""");

    }//GEN-LAST:event_lblRecursosHumanosMouseClicked

    private void btnRecursos_HumanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursos_HumanosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            MUY PRONTO PODRAS \r
                                             HACER UN SEGUIMIENTO DE TUS COLABORADORES \r
                                             EL HOARIO DE ASISTENCIA \r
                                             Y PLANILLA DE SUELDOS Y SALARIOS""");
    }//GEN-LAST:event_btnRecursos_HumanosActionPerformed

    private void lblMarketingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblMarketingKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_lblMarketingKeyTyped

    private void btn_MarketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MarketingActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            PRONTO PODRAS TENER DATOS DE: \r
                                             RANKING DE VENTAS CON GRAFICOS\r
                                             SEGUIMIENTO DE TUS PROMOCIONES\r
                                             Y MUCHO MAS""");
    }//GEN-LAST:event_btn_MarketingActionPerformed

    private void lblMarketingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarketingMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, """
                                            PRONTO PODRAS TENER DATOS DE: \r
                                             RANKING DE VENTAS CON GRAFICOS\r
                                             SEGUIMIENTO DE TUS PROMOCIONES\r
                                             Y MUCHO MAS""");
    }//GEN-LAST:event_lblMarketingMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnContabilidad;
    private javax.swing.JButton btnRecursos_Humanos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btn_Marketing;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblContabilidad;
    private javax.swing.JLabel lblMarketing;
    private javax.swing.JLabel lblRecursosHumanos;
    private javax.swing.JLabel lblVentas;
    // End of variables declaration//GEN-END:variables

}
