/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Reportes;

import DTO.DTOCliente;
import Modelo.CRUD_Reportes;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author LUNA
 */
public class reporte_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form reporte_Clientes
     */
     public DefaultTableModel modeloTabla; //Modelo de la tabla PRODUCTOS  vendidos
    
    public reporte_Clientes() {
        initComponents();
        this.setResizable(false); //Quitar el maximizar y ampliar pantalla
        this.setLocationRelativeTo(null); //LA PANTALLA ESTARA EN EL CENTRO
        modelo_tablaClientes();
        limpiarClientes();
       cargarClientes();
    }
     //Creamos el modelo de la tabla compras
    public void modelo_tablaClientes() {
        //inicializamos la tabla 
        modeloTabla = new DefaultTableModel();
        //Agregamos Nombre
        modeloTabla.addColumn("Nombre");
        //Apellido
        modeloTabla.addColumn("Apellido");
        //Total consumo
        modeloTabla.addColumn("Consumo");
        //Whataspp
        modeloTabla.addColumn("WhatsApp");
        //Colocamos el modelo en el Jtable tabla pedidos No registrados
        tablaClientes.setModel(modeloTabla);

        //Colocamos el ancho de la columna
        //Columna Nombre
        tablaClientes.getColumnModel().getColumn(0).setMaxWidth(150);
        tablaClientes.getColumnModel().getColumn(0).setPreferredWidth(150);
        //Columna Apellido
        tablaClientes.getColumnModel().getColumn(1).setMaxWidth(150);
        tablaClientes.getColumnModel().getColumn(1).setPreferredWidth(150);
         //Columna Consumo
        tablaClientes.getColumnModel().getColumn(2).setMaxWidth(70);
        tablaClientes.getColumnModel().getColumn(2).setPreferredWidth(70);
        //Columna WhatsApp
        tablaClientes.getColumnModel().getColumn(3).setMaxWidth(100);
        tablaClientes.getColumnModel().getColumn(3).setPreferredWidth(100);
        
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CLIENTES TOP");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Consumos", "WhatsApp"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Clientes frecuentes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /***
     * cargamos tabla
     * @param fechaInicio
     * @param fechaFin
     */
    public void cargarClientes() {
        
        //FALTA CARGAR CLIENTES
       
        /*necesito cargar datos*/
        CRUD_Reportes reporte= new CRUD_Reportes();
        ArrayList<DTOCliente> lisPro = reporte.reporteClientes();
        String filas[] = new String[4];
        for (DTOCliente pro : lisPro) {
            filas[0] = pro.getNombre()+"";
            filas[1] = pro.getApellido();
            filas[2] = pro.getContador_compras_hechas()+"";
            filas[3] = pro.getCelular()+"";
            
         modeloTabla.addRow(filas);
        }
        tablaClientes.setModel(modeloTabla);
            
    }
    
       /***
     * Limpiamos la tabla
     */
    private void limpiarClientes()
    {
        modeloTabla.getDataVector().removeAllElements();
        tablaClientes.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
